
image_fe:
   image: blkio10/explorer-ui-free
   tag: "1.0.0"
env_fe:
  containerPort: 5000
  REACT_APP_EXPLORER: "http://localhost:8081"
  cpu: 50m
  memory: 50Mi
  replicas: 1
  revisionHistoryLimit: 3
  app: fe
## API ##
#Docker image and tag for api
image_api:
  repository: blkio10/explorer-free
  tag: "1.0.0"

env_api:
  NODE_ENDPOINT: "http://node-1:22000"
  MONGO_CLIENT_URI: "mongodb://localhost:27017"
  MONGO_DB_NAME: "blk-quorum-dev"
  UI_IP: "http://localhost:5000"
  JAVA_OPTS: ""
    # App migrations
resources_api:
  cpu: "10m"
  cpu_limit: "1"
  memory: "150Mi"
  memory_limit: "3000Mi"

rollingUpdate:
  maxSurge: "1"
  maxUnavailable: "1"

namespaces: "dev"
env: "dev"