# Default values for Traefik
image: traefik
imageTag: 1.5.1
serviceType: LoadBalancer
loadBalancerIP:
#loadBalancerSourceRanges: []
replicas: 3
cpuRequest: 100m
memoryRequest: 100Mi
cpuLimit: 200m
memoryLimit: 300Mi
debug:
  enabled: true
nodeSelector:
  #key: value
tolerations: []
  #- key: "key"
  #operator: "Equal|Exists"
  #value: "value"
  #effect: "NoSchedule|PreferNoSchedule|NoExecute(1.6 only)"
ssl:
  enabled: true
  enforced: true
  defaultCert: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tDQpNSUlFdkFJQkFEQU5CZ2txaGtpRzl3MEJBUUVGQUFTQ0JLWXdnZ1NpQWdFQUFvSUJBUURJSVJIdThaRWRha1BUDQpoUklLTFFiYlRUeUpNdmxMdnNBVDcxQUZPZXNQbGdqRnp6WlBQaFpGYTBwVVVXeFB4cGwzMWxnZmN3MHlndEUwDQp2U0gxRmV6eVZHcS9FQi9uWFhlaUVNYTlLb1pVS1RpZEo3V05EeW8yVE8zdENER2daS3FjalZ6bm0vMlhPaUloDQoxaEU3bExOVFo3RGdyeGlZcURyL1RUOVVDVDRLcHByb2pIbk5JREhzUzJZVXEwZkVXemdNakt0NVlsWWJsT3BjDQpuWXFwek1QWHJGdmhUVlNPeEJ2UytMYWp4L2VYMVp2Q09YeWpicjhRTU1yNHRCSEIyQU5iSEs4WDlnRFRHL3pWDQpnWkdaWmM5dFp4eFlKMnBwK3ZQekxVcnkwLzRxVndSMHlkSWpRbnB6MllacnJkaEM5QVVzVDRlWmJoMXcxbCttDQpMQmF2a0xadEFnTUJBQUVDZ2dFQUo5Mm1rK0dkRmEzNGF1ZEVLN0RDZitjSDJ4RERabHBPS3VwdUYweHRUY0tHDQpadGtiS1hmbHVkaGdpeUZaSVI4ZnJTYU9rVjA2ME1nTVlxUVdZcHNHZzFOYm5FbmJBUnkyV3h0YWE0NVFDZTNZDQpNRDRieFVpekVQUU1KVDZQbkRMUlpiUW5RSi9yU1RlMFd1Y29zYVN5Z0RmVW5UMWorZXp4SzdBNG9FWGpEUDIrDQo4OWIwL2VaSnNPN0RSWmo2SzRjUDFZaVArbjhxTmYvTVVoQkJ4SXorZlFtc3JOUmlINmgzTWcvbmwyZVlYUXBkDQpnN0ZZOUMvVVkxY1pCNmhqclNyUWROcTV5ay9jWXczWmV4TFdWYzRxQWs0dG55dGZFYUxLRHpvNDZmT0lNZE1mDQo4Tyt3cm5WOW1ya01nMHFkNW5uWjVxWm43VFRPM3o4cmcxem0xTXU2UlFLQmdRRHNqNUNqcStnamFVd2dGbSsvDQp5Um5rNm8xQTNiZUNuMDhIL1pHVmFETGgvTjYra0VXaVZQQUY2bkhNRGQ1RHQ3UEZnVk9YNUF2YllYWkFoTW8vDQo2Q3pLblR4WUJGaytJUnJyM25rVnJpRUJManBYTXJSamR6c2JhaDBxUVByalZlbDdWOVZSOGwvczg1Qlk1RzZuDQpGcGhCMm5ramwxaGpmem9QeGlaYVovOCtld0tCZ1FEWWt4dU1UYXI1dUxMQTlNdXFGNEg0TzFoR3BMUlNvUlJkDQpTUTJsMHBQaGlsSy9mRmlRNktkaEQ0SW9kM1Mzdyt0dUFsUEtqd09udHIxSFpNUkg2RCtoN3NkSlQyTnl4UEV4DQpHeS9BNldWbVovVnFFdHdiNUJDVlg0RlphOUI1VFBYVFBEZzRKSzlBNGhxajV6dG5XaUdzTmNVOW8rZ0k5K2VFDQp3RVJKRktHK053S0JnRkVXMFV6Wmc2U0gxcmwxRjI5VmZ4UFNOd05TUFRLQWEzWGd2TVBMU1EzZ1FYWnZPLzl1DQpRQ3kyOWJVdDE4KzhxOW42Lysya0ZWQnBNMERnZy9ldUhaU0NtNG5NUzg4WlNBSXNhN003MGtKMlZ6ZEd3VUVMDQpRTzZmekVtTXByUEE0bDBPZWFneWZpRmFTRlBBVWhIaWsrU1hBRWxyK3JkNGlDMmFEZEdWcm8vN0FvR0FQc0lLDQpOcEwvRzVRaEFIY3ZXVitzZ3ZFM2VHa2I4K0hIayt5cWJzWGhvbmJCMmNrL3BPWTJNcE1hNVgwUUxud3dpZFZVDQowSnEydFcvbjAzdG93V21VbnVraGlLWGZySTlUVVNhT3BQazlML3FxREEzaENKZ0RFalgxdHFMZWEzZ1l1Qmg0DQpOaFN6VURyMCswL3pUOVMzY3o2MXBGSU4yQ04yVEdxbW53TENoK3NDZ1lCZTMwaHBhSGp6eUtLVnVJZFpDVkJHDQpadTcrbndRK3hPRFFEcnJqQVI2SzU4aVo2WkdENEUwVklNTnFoZ21aenBXZUFjcjFzK0VTaUVESnlISEVXdExPDQp3SVlzYmNqSkovNHZvV3dIZy8zZjY2UjdlblcrVXV3UXVod0R6U3h6L21ucStmRDlGTnliTW1YYUYxa3MrV3haDQpJc2Q5TmUrUkVnYWNVYnBXaXNrNlBRPT0NCi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0=
  defaultKey: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tDQpNSUlFdkFJQkFEQU5CZ2txaGtpRzl3MEJBUUVGQUFTQ0JLWXdnZ1NpQWdFQUFvSUJBUURJSVJIdThaRWRha1BUDQpoUklLTFFiYlRUeUpNdmxMdnNBVDcxQUZPZXNQbGdqRnp6WlBQaFpGYTBwVVVXeFB4cGwzMWxnZmN3MHlndEUwDQp2U0gxRmV6eVZHcS9FQi9uWFhlaUVNYTlLb1pVS1RpZEo3V05EeW8yVE8zdENER2daS3FjalZ6bm0vMlhPaUloDQoxaEU3bExOVFo3RGdyeGlZcURyL1RUOVVDVDRLcHByb2pIbk5JREhzUzJZVXEwZkVXemdNakt0NVlsWWJsT3BjDQpuWXFwek1QWHJGdmhUVlNPeEJ2UytMYWp4L2VYMVp2Q09YeWpicjhRTU1yNHRCSEIyQU5iSEs4WDlnRFRHL3pWDQpnWkdaWmM5dFp4eFlKMnBwK3ZQekxVcnkwLzRxVndSMHlkSWpRbnB6MllacnJkaEM5QVVzVDRlWmJoMXcxbCttDQpMQmF2a0xadEFnTUJBQUVDZ2dFQUo5Mm1rK0dkRmEzNGF1ZEVLN0RDZitjSDJ4RERabHBPS3VwdUYweHRUY0tHDQpadGtiS1hmbHVkaGdpeUZaSVI4ZnJTYU9rVjA2ME1nTVlxUVdZcHNHZzFOYm5FbmJBUnkyV3h0YWE0NVFDZTNZDQpNRDRieFVpekVQUU1KVDZQbkRMUlpiUW5RSi9yU1RlMFd1Y29zYVN5Z0RmVW5UMWorZXp4SzdBNG9FWGpEUDIrDQo4OWIwL2VaSnNPN0RSWmo2SzRjUDFZaVArbjhxTmYvTVVoQkJ4SXorZlFtc3JOUmlINmgzTWcvbmwyZVlYUXBkDQpnN0ZZOUMvVVkxY1pCNmhqclNyUWROcTV5ay9jWXczWmV4TFdWYzRxQWs0dG55dGZFYUxLRHpvNDZmT0lNZE1mDQo4Tyt3cm5WOW1ya01nMHFkNW5uWjVxWm43VFRPM3o4cmcxem0xTXU2UlFLQmdRRHNqNUNqcStnamFVd2dGbSsvDQp5Um5rNm8xQTNiZUNuMDhIL1pHVmFETGgvTjYra0VXaVZQQUY2bkhNRGQ1RHQ3UEZnVk9YNUF2YllYWkFoTW8vDQo2Q3pLblR4WUJGaytJUnJyM25rVnJpRUJManBYTXJSamR6c2JhaDBxUVByalZlbDdWOVZSOGwvczg1Qlk1RzZuDQpGcGhCMm5ramwxaGpmem9QeGlaYVovOCtld0tCZ1FEWWt4dU1UYXI1dUxMQTlNdXFGNEg0TzFoR3BMUlNvUlJkDQpTUTJsMHBQaGlsSy9mRmlRNktkaEQ0SW9kM1Mzdyt0dUFsUEtqd09udHIxSFpNUkg2RCtoN3NkSlQyTnl4UEV4DQpHeS9BNldWbVovVnFFdHdiNUJDVlg0RlphOUI1VFBYVFBEZzRKSzlBNGhxajV6dG5XaUdzTmNVOW8rZ0k5K2VFDQp3RVJKRktHK053S0JnRkVXMFV6Wmc2U0gxcmwxRjI5VmZ4UFNOd05TUFRLQWEzWGd2TVBMU1EzZ1FYWnZPLzl1DQpRQ3kyOWJVdDE4KzhxOW42Lysya0ZWQnBNMERnZy9ldUhaU0NtNG5NUzg4WlNBSXNhN003MGtKMlZ6ZEd3VUVMDQpRTzZmekVtTXByUEE0bDBPZWFneWZpRmFTRlBBVWhIaWsrU1hBRWxyK3JkNGlDMmFEZEdWcm8vN0FvR0FQc0lLDQpOcEwvRzVRaEFIY3ZXVitzZ3ZFM2VHa2I4K0hIayt5cWJzWGhvbmJCMmNrL3BPWTJNcE1hNVgwUUxud3dpZFZVDQowSnEydFcvbjAzdG93V21VbnVraGlLWGZySTlUVVNhT3BQazlML3FxREEzaENKZ0RFalgxdHFMZWEzZ1l1Qmg0DQpOaFN6VURyMCswL3pUOVMzY3o2MXBGSU4yQ04yVEdxbW53TENoK3NDZ1lCZTMwaHBhSGp6eUtLVnVJZFpDVkJHDQpadTcrbndRK3hPRFFEcnJqQVI2SzU4aVo2WkdENEUwVklNTnFoZ21aenBXZUFjcjFzK0VTaUVESnlISEVXdExPDQp3SVlzYmNqSkovNHZvV3dIZy8zZjY2UjdlblcrVXV3UXVod0R6U3h6L21ucStmRDlGTnliTW1YYUYxa3MrV3haDQpJc2Q5TmUrUkVnYWNVYnBXaXNrNlBRPT0NCi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0=
acme:
  enabled: false
  email: admin@example.com
  staging: true
  # Save ACME certs to a persistent volume. WARNING: If you do not do this, you will re-request
  # certs every time a pod (re-)starts and you WILL be rate limited!
  persistence:
    enabled: true
    ## If defined, volume.beta.kubernetes.io/storage-class: <storageClass>
    ## Default: volume.alpha.kubernetes.io/storage-class: default
    ##
    # storageClass:
    accessMode: ReadWriteOnce
    size: 1Gi
dashboard:
  enabled: true
  domain: traefik-kimlic.vlytvynov.club
  ingress:
    # annotations:
    #   key: value
  auth:
     basic:
       admin: '$apr1$H6uskkkW$IgXLP6ewTrSuBkTrqE8wj/'
  statistics:
    ## Number of recent errors to show in the ‘Health’ tab
    # recentErrors:
service:
  # annotations:
  #   key: value
  # labels:
  #   key: value
gzip:
  enabled: true
accessLogs:
  enabled: false
  ## Path to the access logs file. If not provided, Traefik defaults it to stdout.
  # filePath: ""
  format: common  # choices are: common, json
# Kubernetes ingress filters
#kubernetes:
#  namespaces:
#  - default
#  labelSelector:
rbac:
  enabled: true
# Enable the /metrics endpoint, for now only supports prometheus
# set to true to enable metric collection by prometheus
metrics:
  prometheus:
    enabled: true
    buckets: "[0.1,0.3,1.2,5.0]"
  datadog:
    enabled: false
#    address: "localhost:8125"
#    pushInterval: 30s
  statsd:
    enabled: false
#    address: "localhost:8125"
#    pushInterval: 30s
