apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  namespace: dev
  name: mongo
spec:
  serviceName: "mongo"
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongodb
        image: mongo:3.4.10
        command:
        - mongod
        - --smallfiles
        ports:
        - containerPort: 27017
          name: peer
