apiVersion: v1
kind: Service
metadata:
  namespace: dev
  name: mongo-db
  labels:
    app: mongo
spec:
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
    name: http
  selector:
    app: mongo
  type: ClusterIP
