apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: api-svc
  namespace: dev
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: api.vlytvynov.club
    http:
      paths:
      - backend:
          serviceName: api-svc
          servicePort: 80