env: dev

stateful_set:
  name: elasticsearch

es:
  version: v6.0
  image: docker.elastic.co/elasticsearch/elasticsearch:6.2.3
  limits:
    cpu: 4000
  ES_JAVA_OPTS: "-Xms2g -Xmx2g"

kibana:
  app_name: kibana
  image: docker.elastic.co/kibana/kibana:6.2.3

# snapshots:
#   cronjob_image: edenlabllc/curator:5.5.1
#   cronjob_formula: "0 */6 * * *"
#   es_repository_name: dev_gcs_repository
#   es_host: elasticsearch
#   es_port: 9200

fluentd:
  flush_interval: 30s
  metrics_port: 24231

ingress: logs.dev.asclepius.com.ua
ingress_pw: logworm:$apr1$cFReyv5D$4QucUXLMaIW.0MbP/hipC/

master:
  configs:
    name: configs
    size: 1Gi
  plugins:
    name: plugins
    size: 1Gi
  persistence:
    name: data
    size: 10Gi
  logs:
    name: logs
    size: 1Gi
