apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.kibana.app_name }}
  namespace: logging
  labels:
    k8s-app: {{ .Values.kibana.app_name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: {{ .Values.kibana.app_name }}
  template:
    metadata:
      labels:
        k8s-app: {{ .Values.kibana.app_name }}
    spec:
      containers:
      - name: {{ .Values.kibana.app_name }}
        image: {{ .Values.kibana.image }}
        resources:
          # need more cpu upon initialization, therefore burstable class
          limits:
            cpu: 1000m
          requests:
            cpu: 100m
        env:
          - name: ELASTICSEARCH_URL
            value: http://{{ .Values.stateful_set.name }}:9200
        ports:
        - containerPort: 5601
          name: ui
          protocol: TCP
      {{- if .Values.nodeSelector }}
      nodeSelector:
        {{ toYaml .Values.nodeSelector | indent 8 }}
      {{- end }}
