apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.kibana.app_name }}
  namespace: logging
  labels:
    k8s-app: {{ .Values.kibana.app_name }}
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5601
    name: http
  selector:
    k8s-app: {{ .Values.kibana.app_name }}
  type: ClusterIP
