apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fe-exporter
  labels:
    app:  {{ .Values.env_fe.app}}
    version: "{{ .Values.image_fe.tag}}"
spec:
  replicas: {{ .Values.env_fe.replicas}}
  revisionHistoryLimit: {{ .Values.env_fe.revisionHistoryLimit}}
  selector:
    matchLabels:
      app: {{ .Values.env_fe.app}}
  template:
    metadata:
      labels:
        app:  {{ .Values.env_fe.app}}
        version: "{{ .Values.image_fe.tag}}"
    spec:
      containers:
      - name: ui-exporter
        image: {{ .Values.image_fe.image}}:{{ .Values.image_fe.tag}}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: {{ .Values.env_fe.containerPort}}
          protocol: TCP
        env:
        - name: REACT_APP_EXPLORER
          value:  "{{ .Values.env_fe.REACT_APP_EXPLORER}}"
        resources:
          requests:
            cpu: {{ .Values.env_fe.cpu}}
            memory: {{ .Values.env_fe.memory}}
    #  nodeSelector:
    #    node: {{ .Values.env }}