apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespaces }}
  name: fe-exporter-svc
  labels:
    app: fe
spec:
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
    name: public
  selector:
    app: fe
  type: ClusterIP
