apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: api-svc
  namespace: attestation
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: ap-api-dev.kimlic.com
    http:
      paths:
      - backend:
          serviceName: api-svc
          servicePort: 80