
## API ##
#Docker image and tag for api
image_api:
  repository: kimlictr/quorum
  tag: "node1-dev"

env_api:
    CURRENT_NODE_IP: "40.118.69.43"
    R_PORT: "22000"
    W_PORT: "22001"
    C_PORT: "22002"
    RA_PORT: "22003"
    NODE_MANAGER_PORT: "22004"
    WS_PORT: "22005"
    RAFT_ID: "1"
    NETID: "36606"
    NODE_NAME: "kimlic-1"
    # App migrations
resources_api:
  cpu: "10m"
  cpu_limit: "2"
  memory: "150Mi"
  memory_limit: "3000Mi"

rollingUpdate:
  maxSurge: "1"
  maxUnavailable: "1"

port_svc: "22000"
port: "22000"
node: "kimlic-1"
env: "dev"
#ip: "10.0.10.10"