
## API ##
#Docker image and tag for api
image_api:
  repository: kimlictr/quorum
  tag: "master-prod"

env_api:
    CURRENT_NODE_IP: "23.97.133.143"
    R_PORT: "22000"
    W_PORT: "22001"
    C_PORT: "22002"
    RA_PORT: "22003"
    NODE_MANAGER_PORT: "22004"
    WS_PORT: "22005"
    RAFT_ID: "1"
    NETID: "60404"
    NODE_NAME: "node-master"
    # App migrations
resources_api:
  cpu: "10m"
  cpu_limit: "2"
  memory: "150Mi"
  memory_limit: "3000Mi"

rollingUpdate:
  maxSurge: "1"
  maxUnavailable: "1"

port_svc: "22000"
port: "22000"
node: "node-master"
env: "prod"
ip: "23.97.133.143"