
## API ##
#Docker image and tag for api
image_api:
  repository: kimlictr/quorum
  tag: "node2-0.0.1"

env_api:
    CORE_node-2_NETWORKID: node-2
    CORE_NODE_IP: node-2
    CORE_MASTERNODE_IP: node-1
    # App migrations
resources_api:
  cpu: "10m"
  cpu_limit: "2"
  memory: "150Mi"
  memory_limit: "3000Mi"

rollingUpdate:
  maxSurge: "1"
  maxUnavailable: "1"

port_svc: "22001"
port: "22000"
node: "node-2"
env: "dev"
