
## API ##
#Docker image and tag for api
image_api:
  repository: kimlictr/quorum
  tag: "att-dev-1"

env_api:
    CURRENT_NODE_IP: "40.118.56.164"
    R_PORT: "22000"
    W_PORT: "22001"
    C_PORT: "22002"
    RA_PORT: "22003"
    NM_PORT: "22004"
    RAFTID: "2"
    NETID: "36606"
    NODENAME: "att-slave"
    MASTER_IP: "40.118.69.43"
    MC_PORT: "22002"

    # App migrations
resources_api:
  cpu: "10m"
  cpu_limit: "2"
  memory: "150Mi"
  memory_limit: "3000Mi"

rollingUpdate:
  maxSurge: "1"
  maxUnavailable: "1"

port_svc: "22000"
port: "22000"
node: "att-slave"
env: "dev"
ip: "40.118.56.164"
slave: true