
## API ##
#Docker image and tag for api
image_api:
  repository: kimlictr/quorum
  tag: "att-test"

env_api:
    CURRENT_NODE_IP: "13.81.243.31"
    R_PORT: "22000"
    W_PORT: "22001"
    C_PORT: "22002"
    RA_PORT: "22003"
    NM_PORT: "22004"
    RAFTID: "2"
    NETID: "13602"
    NODENAME: "att-test-slave"
    MASTER_IP: "51.144.109.43"
    MC_PORT: "22002"

    # App migrations
resources_api:
  cpu: "10m"
  cpu_limit: "2"
  memory: "150Mi"
  memory_limit: "3000Mi"

rollingUpdate:
  maxSurge: "1"
  maxUnavailable: "1"

port_svc: "22000"
port: "22000"
node: "att-slave-test"
env: "test"
ip: "13.81.243.31"
slave: true