apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.env }}
  name: node-lb
  labels:
    app: {{ .Values.node }}
spec:
  ports:
  - port: 22000
    targetPort: 22000
    protocol: TCP
  selector:
    app: {{ .Values.node }}
  type: LoadBalancer
