apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.env }}
  name: {{ .Values.node }}
  labels:
    app:  {{ .Values.node }}
spec:
  clusterIP: {{ .Values.ip }}
  ports:
  - port:  {{ .Values.port_svc }}
    targetPort: {{ .Values.port }}
    protocol: TCP
  selector:
    app: {{ .Values.node }}
  type: ClusterIP
