
## API ##
#Docker image and tag for api
image_api:
  repository: kimlictr/mobile_api
  tag: "0.54.1"

env_api:
  # Phoenix application
  SECRET_KEY:                                     "%s$lddL35j9~~uDN@n8ub1#mJHTBb7hlat#ooz?TvcjA5{mn35$d2GJFN2~MT#99"
  ERLANG_COOKIE:                                  "mioPh52jUyGxrUPIhfvaMrTP5oM3qIGx"
  PORT:                                           "4000"
  # Redis
  REDIS_URI:                                      "redis://kimlic-dev.redis.cache.windows.net:6380,password=ImlzxMAf7fp5s5ztw5qjK28WxUXIFS6J36iy7sO64vc=,ssl=True,abortConnect=False"
  REDIS_PASSWORD:                                 "ImlzxMAf7fp5s5ztw5qjK28WxUXIFS6J36iy7sO64vc"
  # RabbitMQ
  RABBITMQ_HOST:                                  "rabbitmq.dev.svc.cluster.local"
  RABBITMQ_USERNAME:                              "user"
  RABBITMQ_PASSWORD:                              "A4KgN43E6m"
  # Email
  AMAZON_SES_REGION_ENDPOINT:                     "eu-west-1"
  AMAZON_SES_ACCESS_KEY:                          "AKIAJXIR6LE2FNZFBTFA"
  AMAZON_SES_SECRET_KEY:                          "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"
  EMAIL_CREATE_PROFILE_FROM_EMAIL:                "verification@kimlic.com"
  EMAIL_CREATE_PROFILE_FROM_NAME:                 "Kimlic"
  EMAIL_CREATE_PROFILE_SUBJECT:                   "Kimlic - User email verification"
  # Verifications
  VERIFICATION_EMAIL_TTL:                         "86400" # 1 day in seconds
  VERIFICATION_PHONE_TTL:                         "3600" # 1 hour in seconds
  # Twilio
  TWILIO_ACCOUNT_SID:                             "AC07bf3306b3acf8fe318a5f60ec24466f"
  TWILIO_AUTH_TOKEN:                              "a4cb70766ad8b8bfbe47fe4f6bce0f22"
  # SMS rate limit
  RATE_LIMIT_CREATE_PHONE_VERIFICATION_ATTEMPTS:  "5"
  RATE_LIMIT_CREATE_PHONE_VERIFICATION_TIMEOUT:   "86400" # 1 day in seconds
  # Quorum
  QUORUM_URI:                                     "40.115.43.126:22000"
  QUORUM_ALLOWED_RPC_METHODS:                     "web3_clientVersion,eth_call,eth_sendTransaction,eth_sendRawTransaction,eth_getTransactionCount,getTransactionReceipt,personal_newAccount"
  # Attestation parties addresses
  VERIFF_AP_ADDRESS:                              "0xe414ba511451ebbfc91de224ede2dea4c51d3d07"
  VERIFF_AP_PASSWORD:                             "Veriffp@ssw0rd"
  KIMLIC_AP_ADDRESS:                              "0x0b5d5e3403128e29b3b55a1c8b518b17dcc0fb3a"
  KIMLIC_AP_PASSWORD:                             "Kimlicp@ssw0rd"
  # Context storage address
  CONTEXT_STORAGE_ADDRESS:                        "0xf928fd62717792c14e661749bfa74821a563d1b4"
resources_api:
  cpu: "10m"
  cpu_limit: "1"
  memory: "150Mi"
  memory_limit: "300Mi"

rollingUpdate:
  maxSurge: "1"
  maxUnavailable: "1"