
## API ##
#Docker image and tag for api
image_api:
  repository: kimlictr/mobile_api
  tag: "0.52.15"

env_api:
  SECRET_KEY: "%s$lddL35j9~~uDN@n8ub1#mJHTBb7hlat#ooz?TvcjA5{mn35$d2GJFN2~MT#99"
  ERLANG_COOKIE: "mioPh52jUyGxrUPIhfvaMrTP5oM3qIGx"
  PORT: "4000"
 # DB_HOST: "db-svc"
 # DB_PORT: "5432"
 # DB_USER: "db"
 # DB_NAME: "kimkublic"
 # DB_PASSWORD: "1"
 # Redis
  REDIS_URI: "redis://:23ZKbrKnRA@redis-master.dev.svc.cluster.local:6379"
  REDIS_PASSWORD: "23ZKbrKnRA"
  #SECRET_KEY: "MAJJSvyjkz"
  # RabbitMQ
 # RABBITMQ_URI: "amqp://user:68fZGV2MnB@rabbitmq?heartbeat=30"
  RABBITMQ_HOST: "rabbitmq.dev.svc.cluster.local"
  RABBITMQ_USERNAME: "test"
  RABBITMQ_PASSWORD: "test"
  # Email
  AMAZON_SES_REGION_ENDPOINT: "eu-west-1"
  AMAZON_SES_ACCESS_KEY: "AKIAJXIR6LE2FNZFBTFA"
  AMAZON_SES_SECRET_KEY: "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"
  EMAIL_CREATE_PROFILE_FROM_EMAIL: "verification@kimlic.com"
  EMAIL_CREATE_PROFILE_FROM_NAME: "Kimlic"
  EMAIL_CREATE_PROFILE_SUBJECT: "Kimlic - User email verification"
  # Verifications
  VERIFICATION_EMAIL_TTL: "86400" # 1 day in seconds
  VERIFICATION_PHONE_TTL: "3600" # 1 hour in seconds
  # Twilio
  TWILIO_ACCOUNT_SID: "AC07bf3306b3acf8fe318a5f60ec24466f"
  TWILIO_AUTH_TOKEN: "a4cb70766ad8b8bfbe47fe4f6bce0f22"
  # SMS rate limit
  RATE_LIMIT_CREATE_PHONE_VERIFICATION_TIMEOUT: "86400" # 1 day in seconds
  RATE_LIMIT_CREATE_PHONE_VERIFICATION_ATTEMPTS: "5"
  # Quorum
  QUORUM_URI: "40.115.43.126:22000"
  AUTHORIZATION_SALT: "1234567890"
  KIMLIC_AP_ADDRESS: "0x0b5d5e3403128e29b3b55a1c8b518b17dcc0fb3a"
  KIMLIC_AP_PASSWORD: "Kimlicp@ssw0rd"
  CONTEXT_STORAGE_ADDRESS: "0xf928fd62717792c14e661749bfa74821a563d1b4"
  QUORUM_ALLOWED_RPC_METHODS: "web3_clientVersion,eth_call,eth_sendTransaction,eth_sendRawTransaction,eth_getTransactionCount"
  VERIFF_AP_ADDRESS: "0xe414ba511451ebbfc91de224ede2dea4c51d3d07"
  VERIFF_AP_PASSWORD: "Veriffp@ssw0rd"
    # App migrations
resources_api:
  cpu: "10m"
  cpu_limit: "1"
  memory: "150Mi"
  memory_limit: "300Mi"

rollingUpdate:
  maxSurge: "1"
  maxUnavailable: "1"