
## DB ##
image_db:
  repository: postgres
  tag: 10.4

env_db:
  app: "postgresql"
  version: "10.4"
  #DB_USER: API - POSTGRES_DB: DB
  POSTGRES_USER: "db"
  #DB_PASSWORD: API and DB
  POSTGRES_PASSWORD: "1"
  PGDATA: "/var/lib/postgresql/data"
  #DB_NAME: API
  POSTGRES_DB: "kimlic"
  REPLICATOR_USER: "pghoard"
  REPLICATOR_PASSWORD: "1"
  db_port: "5432"

resources_db:
  cpu: "50m"
  memory: "112Mi"
  limits_memory: "1Gi"
  storage: "10Gi"

node: dev

volumeName: pv-postgres
storageClass: "dev"